/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;

import trzye.zrzutka.jooq.model.tables.AndroidMetadata;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AndroidMetadataRecord extends TableRecordImpl<AndroidMetadataRecord> implements Record1<String> {

	private static final long serialVersionUID = 1413605140;

	/**
	 * Setter for <code>android_metadata.locale</code>.
	 */
	public void setLocale(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>android_metadata.locale</code>.
	 */
	public String getLocale() {
		return (String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<String> fieldsRow() {
		return (Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<String> valuesRow() {
		return (Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AndroidMetadata.ANDROID_METADATA.LOCALE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getLocale();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AndroidMetadataRecord value1(String value) {
		setLocale(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AndroidMetadataRecord values(String value1) {
		value1(value1);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AndroidMetadataRecord
	 */
	public AndroidMetadataRecord() {
		super(AndroidMetadata.ANDROID_METADATA);
	}

	/**
	 * Create a detached, initialised AndroidMetadataRecord
	 */
	public AndroidMetadataRecord(String locale) {
		super(AndroidMetadata.ANDROID_METADATA);

		setValue(0, locale);
	}
}
