/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import trzye.zrzutka.jooq.model.tables.Contribution;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributionRecord extends UpdatableRecordImpl<ContributionRecord> implements Record7<Long, Integer, Date, Integer, Date, Long, String> {

	private static final long serialVersionUID = 2106261819;

	/**
	 * Setter for <code>contribution.chargeUniqueNumberForSorting</code>.
	 */
	public void setChargeuniquenumberforsorting(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>contribution.chargeUniqueNumberForSorting</code>.
	 */
	public Long getChargeuniquenumberforsorting() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>contribution.colorId</code>.
	 */
	public void setColorid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>contribution.colorId</code>.
	 */
	public Integer getColorid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>contribution.endDate</code>.
	 */
	public void setEnddate(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>contribution.endDate</code>.
	 */
	public Date getEnddate() {
		return (Date) getValue(2);
	}

	/**
	 * Setter for <code>contribution.id</code>.
	 */
	public void setId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>contribution.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>contribution.startDate</code>.
	 */
	public void setStartdate(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>contribution.startDate</code>.
	 */
	public Date getStartdate() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>contribution.summary_id</code>.
	 */
	public void setSummaryId(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>contribution.summary_id</code>.
	 */
	public Long getSummaryId() {
		return (Long) getValue(5);
	}

	/**
	 * Setter for <code>contribution.title</code>.
	 */
	public void setTitle(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>contribution.title</code>.
	 */
	public String getTitle() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Integer, Date, Integer, Date, Long, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Integer, Date, Integer, Date, Long, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Contribution.CONTRIBUTION.CHARGEUNIQUENUMBERFORSORTING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Contribution.CONTRIBUTION.COLORID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return Contribution.CONTRIBUTION.ENDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Contribution.CONTRIBUTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return Contribution.CONTRIBUTION.STARTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return Contribution.CONTRIBUTION.SUMMARY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Contribution.CONTRIBUTION.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getChargeuniquenumberforsorting();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getColorid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getEnddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getStartdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getSummaryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value1(Long value) {
		setChargeuniquenumberforsorting(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value2(Integer value) {
		setColorid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value3(Date value) {
		setEnddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value4(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value5(Date value) {
		setStartdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value6(Long value) {
		setSummaryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value7(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord values(Long value1, Integer value2, Date value3, Integer value4, Date value5, Long value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContributionRecord
	 */
	public ContributionRecord() {
		super(Contribution.CONTRIBUTION);
	}

	/**
	 * Create a detached, initialised ContributionRecord
	 */
	public ContributionRecord(Long chargeuniquenumberforsorting, Integer colorid, Date enddate, Integer id, Date startdate, Long summaryId, String title) {
		super(Contribution.CONTRIBUTION);

		setValue(0, chargeuniquenumberforsorting);
		setValue(1, colorid);
		setValue(2, enddate);
		setValue(3, id);
		setValue(4, startdate);
		setValue(5, summaryId);
		setValue(6, title);
	}
}
