/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import trzye.zrzutka.jooq.model.tables.Friend;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FriendRecord extends UpdatableRecordImpl<FriendRecord> implements Record5<Integer, String, Integer, String, String> {

	private static final long serialVersionUID = -1301657626;

	/**
	 * Setter for <code>friend.colorId</code>.
	 */
	public void setColorid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>friend.colorId</code>.
	 */
	public Integer getColorid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>friend.contactInformation</code>.
	 */
	public void setContactinformation(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>friend.contactInformation</code>.
	 */
	public String getContactinformation() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>friend.id</code>.
	 */
	public void setId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>friend.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>friend.nickname</code>.
	 */
	public void setNickname(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>friend.nickname</code>.
	 */
	public String getNickname() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>friend.paymentInformation</code>.
	 */
	public void setPaymentinformation(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>friend.paymentInformation</code>.
	 */
	public String getPaymentinformation() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Integer, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Integer, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Friend.FRIEND.COLORID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Friend.FRIEND.CONTACTINFORMATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Friend.FRIEND.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Friend.FRIEND.NICKNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Friend.FRIEND.PAYMENTINFORMATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getColorid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getContactinformation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getNickname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPaymentinformation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FriendRecord value1(Integer value) {
		setColorid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FriendRecord value2(String value) {
		setContactinformation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FriendRecord value3(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FriendRecord value4(String value) {
		setNickname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FriendRecord value5(String value) {
		setPaymentinformation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FriendRecord values(Integer value1, String value2, Integer value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FriendRecord
	 */
	public FriendRecord() {
		super(Friend.FRIEND);
	}

	/**
	 * Create a detached, initialised FriendRecord
	 */
	public FriendRecord(Integer colorid, String contactinformation, Integer id, String nickname, String paymentinformation) {
		super(Friend.FRIEND);

		setValue(0, colorid);
		setValue(1, contactinformation);
		setValue(2, id);
		setValue(3, nickname);
		setValue(4, paymentinformation);
	}
}
