/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import trzye.zrzutka.jooq.model.tables.Purchase;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseRecord extends UpdatableRecordImpl<PurchaseRecord> implements Record5<Integer, Long, Integer, String, Long> {

	private static final long serialVersionUID = -3601917;

	/**
	 * Setter for <code>purchase.colorId</code>.
	 */
	public void setColorid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>purchase.colorId</code>.
	 */
	public Integer getColorid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>purchase.contribution_id</code>.
	 */
	public void setContributionId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>purchase.contribution_id</code>.
	 */
	public Long getContributionId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>purchase.id</code>.
	 */
	public void setId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>purchase.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>purchase.name</code>.
	 */
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>purchase.name</code>.
	 */
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>purchase.price</code>.
	 */
	public void setPrice(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>purchase.price</code>.
	 */
	public Long getPrice() {
		return (Long) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Long, Integer, String, Long> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Long, Integer, String, Long> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Purchase.PURCHASE.COLORID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return Purchase.PURCHASE.CONTRIBUTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Purchase.PURCHASE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Purchase.PURCHASE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return Purchase.PURCHASE.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getColorid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getContributionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PurchaseRecord value1(Integer value) {
		setColorid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PurchaseRecord value2(Long value) {
		setContributionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PurchaseRecord value3(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PurchaseRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PurchaseRecord value5(Long value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PurchaseRecord values(Integer value1, Long value2, Integer value3, String value4, Long value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PurchaseRecord
	 */
	public PurchaseRecord() {
		super(Purchase.PURCHASE);
	}

	/**
	 * Create a detached, initialised PurchaseRecord
	 */
	public PurchaseRecord(Integer colorid, Long contributionId, Integer id, String name, Long price) {
		super(Purchase.PURCHASE);

		setValue(0, colorid);
		setValue(1, contributionId);
		setValue(2, id);
		setValue(3, name);
		setValue(4, price);
	}
}
