/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import trzye.zrzutka.jooq.model.tables.Summary;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SummaryRecord extends UpdatableRecordImpl<SummaryRecord> implements Record7<Integer, Integer, Integer, Short, Short, Long, String> {

	private static final long serialVersionUID = 1667938691;

	/**
	 * Setter for <code>summary.colorPriceSumId</code>.
	 */
	public void setColorpricesumid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>summary.colorPriceSumId</code>.
	 */
	public Integer getColorpricesumid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>summary.colorSummaryId</code>.
	 */
	public void setColorsummaryid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>summary.colorSummaryId</code>.
	 */
	public Integer getColorsummaryid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>summary.id</code>.
	 */
	public void setId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>summary.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>summary.isSortedDescending</code>.
	 */
	public void setIssorteddescending(Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>summary.isSortedDescending</code>.
	 */
	public Short getIssorteddescending() {
		return (Short) getValue(3);
	}

	/**
	 * Setter for <code>summary.preciseCalculation</code>.
	 */
	public void setPrecisecalculation(Short value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>summary.preciseCalculation</code>.
	 */
	public Short getPrecisecalculation() {
		return (Short) getValue(4);
	}

	/**
	 * Setter for <code>summary.priceSum</code>.
	 */
	public void setPricesum(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>summary.priceSum</code>.
	 */
	public Long getPricesum() {
		return (Long) getValue(5);
	}

	/**
	 * Setter for <code>summary.sortedColumn</code>.
	 */
	public void setSortedcolumn(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>summary.sortedColumn</code>.
	 */
	public String getSortedcolumn() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, Integer, Short, Short, Long, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, Integer, Short, Short, Long, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Summary.SUMMARY.COLORPRICESUMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Summary.SUMMARY.COLORSUMMARYID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Summary.SUMMARY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field4() {
		return Summary.SUMMARY.ISSORTEDDESCENDING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field5() {
		return Summary.SUMMARY.PRECISECALCULATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return Summary.SUMMARY.PRICESUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Summary.SUMMARY.SORTEDCOLUMN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getColorpricesumid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getColorsummaryid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value4() {
		return getIssorteddescending();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value5() {
		return getPrecisecalculation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getPricesum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSortedcolumn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SummaryRecord value1(Integer value) {
		setColorpricesumid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SummaryRecord value2(Integer value) {
		setColorsummaryid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SummaryRecord value3(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SummaryRecord value4(Short value) {
		setIssorteddescending(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SummaryRecord value5(Short value) {
		setPrecisecalculation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SummaryRecord value6(Long value) {
		setPricesum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SummaryRecord value7(String value) {
		setSortedcolumn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SummaryRecord values(Integer value1, Integer value2, Integer value3, Short value4, Short value5, Long value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SummaryRecord
	 */
	public SummaryRecord() {
		super(Summary.SUMMARY);
	}

	/**
	 * Create a detached, initialised SummaryRecord
	 */
	public SummaryRecord(Integer colorpricesumid, Integer colorsummaryid, Integer id, Short issorteddescending, Short precisecalculation, Long pricesum, String sortedcolumn) {
		super(Summary.SUMMARY);

		setValue(0, colorpricesumid);
		setValue(1, colorsummaryid);
		setValue(2, id);
		setValue(3, issorteddescending);
		setValue(4, precisecalculation);
		setValue(5, pricesum);
		setValue(6, sortedcolumn);
	}
}
