/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Charge implements Serializable {

	private static final long serialVersionUID = 1157330240;

	private Long    amountpaid;
	private Long    amounttopay;
	private Long    chargeuniquenumberforsorting;
	private Long    chargedId;
	private Integer id;
	private Long    purchaseId;

	public Charge() {}

	public Charge(Charge value) {
		this.amountpaid = value.amountpaid;
		this.amounttopay = value.amounttopay;
		this.chargeuniquenumberforsorting = value.chargeuniquenumberforsorting;
		this.chargedId = value.chargedId;
		this.id = value.id;
		this.purchaseId = value.purchaseId;
	}

	public Charge(
		Long    amountpaid,
		Long    amounttopay,
		Long    chargeuniquenumberforsorting,
		Long    chargedId,
		Integer id,
		Long    purchaseId
	) {
		this.amountpaid = amountpaid;
		this.amounttopay = amounttopay;
		this.chargeuniquenumberforsorting = chargeuniquenumberforsorting;
		this.chargedId = chargedId;
		this.id = id;
		this.purchaseId = purchaseId;
	}

	public Long getAmountpaid() {
		return this.amountpaid;
	}

	public void setAmountpaid(Long amountpaid) {
		this.amountpaid = amountpaid;
	}

	public Long getAmounttopay() {
		return this.amounttopay;
	}

	public void setAmounttopay(Long amounttopay) {
		this.amounttopay = amounttopay;
	}

	public Long getChargeuniquenumberforsorting() {
		return this.chargeuniquenumberforsorting;
	}

	public void setChargeuniquenumberforsorting(Long chargeuniquenumberforsorting) {
		this.chargeuniquenumberforsorting = chargeuniquenumberforsorting;
	}

	public Long getChargedId() {
		return this.chargedId;
	}

	public void setChargedId(Long chargedId) {
		this.chargedId = chargedId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(Long purchaseId) {
		this.purchaseId = purchaseId;
	}
}
