/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contributor implements Serializable {

	private static final long serialVersionUID = 142618380;

	private Long    contributionId;
	private Long    friendId;
	private Integer id;

	public Contributor() {}

	public Contributor(Contributor value) {
		this.contributionId = value.contributionId;
		this.friendId = value.friendId;
		this.id = value.id;
	}

	public Contributor(
		Long    contributionId,
		Long    friendId,
		Integer id
	) {
		this.contributionId = contributionId;
		this.friendId = friendId;
		this.id = id;
	}

	public Long getContributionId() {
		return this.contributionId;
	}

	public void setContributionId(Long contributionId) {
		this.contributionId = contributionId;
	}

	public Long getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Long friendId) {
		this.friendId = friendId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
}
