/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contribution implements Serializable {

	private static final long serialVersionUID = -542767019;

	private Long    chargeuniquenumberforsorting;
	private Integer colorid;
	private Date    enddate;
	private Integer id;
	private Date    startdate;
	private Long    summaryId;
	private String  title;

	public Contribution() {}

	public Contribution(Contribution value) {
		this.chargeuniquenumberforsorting = value.chargeuniquenumberforsorting;
		this.colorid = value.colorid;
		this.enddate = value.enddate;
		this.id = value.id;
		this.startdate = value.startdate;
		this.summaryId = value.summaryId;
		this.title = value.title;
	}

	public Contribution(
		Long    chargeuniquenumberforsorting,
		Integer colorid,
		Date    enddate,
		Integer id,
		Date    startdate,
		Long    summaryId,
		String  title
	) {
		this.chargeuniquenumberforsorting = chargeuniquenumberforsorting;
		this.colorid = colorid;
		this.enddate = enddate;
		this.id = id;
		this.startdate = startdate;
		this.summaryId = summaryId;
		this.title = title;
	}

	public Long getChargeuniquenumberforsorting() {
		return this.chargeuniquenumberforsorting;
	}

	public void setChargeuniquenumberforsorting(Long chargeuniquenumberforsorting) {
		this.chargeuniquenumberforsorting = chargeuniquenumberforsorting;
	}

	public Integer getColorid() {
		return this.colorid;
	}

	public void setColorid(Integer colorid) {
		this.colorid = colorid;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Long getSummaryId() {
		return this.summaryId;
	}

	public void setSummaryId(Long summaryId) {
		this.summaryId = summaryId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
}
