/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Friend implements Serializable {

	private static final long serialVersionUID = 2043690053;

	private Integer colorid;
	private String  contactinformation;
	private Integer id;
	private String  nickname;
	private String  paymentinformation;

	public Friend() {}

	public Friend(Friend value) {
		this.colorid = value.colorid;
		this.contactinformation = value.contactinformation;
		this.id = value.id;
		this.nickname = value.nickname;
		this.paymentinformation = value.paymentinformation;
	}

	public Friend(
		Integer colorid,
		String  contactinformation,
		Integer id,
		String  nickname,
		String  paymentinformation
	) {
		this.colorid = colorid;
		this.contactinformation = contactinformation;
		this.id = id;
		this.nickname = nickname;
		this.paymentinformation = paymentinformation;
	}

	public Integer getColorid() {
		return this.colorid;
	}

	public void setColorid(Integer colorid) {
		this.colorid = colorid;
	}

	public String getContactinformation() {
		return this.contactinformation;
	}

	public void setContactinformation(String contactinformation) {
		this.contactinformation = contactinformation;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPaymentinformation() {
		return this.paymentinformation;
	}

	public void setPaymentinformation(String paymentinformation) {
		this.paymentinformation = paymentinformation;
	}
}
