/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Purchase implements Serializable {

	private static final long serialVersionUID = 248891114;

	private Integer colorid;
	private Long    contributionId;
	private Integer id;
	private String  name;
	private Long    price;

	public Purchase() {}

	public Purchase(Purchase value) {
		this.colorid = value.colorid;
		this.contributionId = value.contributionId;
		this.id = value.id;
		this.name = value.name;
		this.price = value.price;
	}

	public Purchase(
		Integer colorid,
		Long    contributionId,
		Integer id,
		String  name,
		Long    price
	) {
		this.colorid = colorid;
		this.contributionId = contributionId;
		this.id = id;
		this.name = name;
		this.price = price;
	}

	public Integer getColorid() {
		return this.colorid;
	}

	public void setColorid(Integer colorid) {
		this.colorid = colorid;
	}

	public Long getContributionId() {
		return this.contributionId;
	}

	public void setContributionId(Long contributionId) {
		this.contributionId = contributionId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}
}
