/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import trzye.zrzutka.jooq.model.tables.AndroidMetadata;
import trzye.zrzutka.jooq.model.tables.Charge;
import trzye.zrzutka.jooq.model.tables.Contribution;
import trzye.zrzutka.jooq.model.tables.Contributor;
import trzye.zrzutka.jooq.model.tables.Friend;
import trzye.zrzutka.jooq.model.tables.Purchase;
import trzye.zrzutka.jooq.model.tables.SqliteSequence;
import trzye.zrzutka.jooq.model.tables.Summary;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = -2016738983;

	/**
	 * The reference instance of <code></code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			AndroidMetadata.ANDROID_METADATA,
			Charge.CHARGE,
			Contribution.CONTRIBUTION,
			Contributor.CONTRIBUTOR,
			Friend.FRIEND,
			Purchase.PURCHASE,
			SqliteSequence.SQLITE_SEQUENCE,
			Summary.SUMMARY);
	}
}
