/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model;


import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import trzye.zrzutka.jooq.model.tables.Charge;
import trzye.zrzutka.jooq.model.tables.Contribution;
import trzye.zrzutka.jooq.model.tables.Contributor;
import trzye.zrzutka.jooq.model.tables.Friend;
import trzye.zrzutka.jooq.model.tables.Purchase;
import trzye.zrzutka.jooq.model.tables.Summary;
import trzye.zrzutka.jooq.model.tables.records.ChargeRecord;
import trzye.zrzutka.jooq.model.tables.records.ContributionRecord;
import trzye.zrzutka.jooq.model.tables.records.ContributorRecord;
import trzye.zrzutka.jooq.model.tables.records.FriendRecord;
import trzye.zrzutka.jooq.model.tables.records.PurchaseRecord;
import trzye.zrzutka.jooq.model.tables.records.SummaryRecord;


/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<ChargeRecord> PK_CHARGE = UniqueKeys0.PK_CHARGE;
	public static final UniqueKey<ContributionRecord> PK_CONTRIBUTION = UniqueKeys0.PK_CONTRIBUTION;
	public static final UniqueKey<ContributorRecord> PK_CONTRIBUTOR = UniqueKeys0.PK_CONTRIBUTOR;
	public static final UniqueKey<FriendRecord> PK_FRIEND = UniqueKeys0.PK_FRIEND;
	public static final UniqueKey<PurchaseRecord> PK_PURCHASE = UniqueKeys0.PK_PURCHASE;
	public static final UniqueKey<SummaryRecord> PK_SUMMARY = UniqueKeys0.PK_SUMMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<ChargeRecord> PK_CHARGE = createUniqueKey(Charge.CHARGE, Charge.CHARGE.ID);
		public static final UniqueKey<ContributionRecord> PK_CONTRIBUTION = createUniqueKey(Contribution.CONTRIBUTION, Contribution.CONTRIBUTION.ID);
		public static final UniqueKey<ContributorRecord> PK_CONTRIBUTOR = createUniqueKey(Contributor.CONTRIBUTOR, Contributor.CONTRIBUTOR.ID);
		public static final UniqueKey<FriendRecord> PK_FRIEND = createUniqueKey(Friend.FRIEND, Friend.FRIEND.ID);
		public static final UniqueKey<PurchaseRecord> PK_PURCHASE = createUniqueKey(Purchase.PURCHASE, Purchase.PURCHASE.ID);
		public static final UniqueKey<SummaryRecord> PK_SUMMARY = createUniqueKey(Summary.SUMMARY, Summary.SUMMARY.ID);
	}
}
