/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model;


import javax.annotation.Generated;

import trzye.zrzutka.jooq.model.tables.AndroidMetadata;
import trzye.zrzutka.jooq.model.tables.Charge;
import trzye.zrzutka.jooq.model.tables.Contribution;
import trzye.zrzutka.jooq.model.tables.Contributor;
import trzye.zrzutka.jooq.model.tables.Friend;
import trzye.zrzutka.jooq.model.tables.Purchase;
import trzye.zrzutka.jooq.model.tables.SqliteSequence;
import trzye.zrzutka.jooq.model.tables.Summary;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table android_metadata
	 */
	public static final AndroidMetadata ANDROID_METADATA = trzye.zrzutka.jooq.model.tables.AndroidMetadata.ANDROID_METADATA;

	/**
	 * The table charge
	 */
	public static final Charge CHARGE = trzye.zrzutka.jooq.model.tables.Charge.CHARGE;

	/**
	 * The table contribution
	 */
	public static final Contribution CONTRIBUTION = trzye.zrzutka.jooq.model.tables.Contribution.CONTRIBUTION;

	/**
	 * The table contributor
	 */
	public static final Contributor CONTRIBUTOR = trzye.zrzutka.jooq.model.tables.Contributor.CONTRIBUTOR;

	/**
	 * The table friend
	 */
	public static final Friend FRIEND = trzye.zrzutka.jooq.model.tables.Friend.FRIEND;

	/**
	 * The table purchase
	 */
	public static final Purchase PURCHASE = trzye.zrzutka.jooq.model.tables.Purchase.PURCHASE;

	/**
	 * The table sqlite_sequence
	 */
	public static final SqliteSequence SQLITE_SEQUENCE = trzye.zrzutka.jooq.model.tables.SqliteSequence.SQLITE_SEQUENCE;

	/**
	 * The table summary
	 */
	public static final Summary SUMMARY = trzye.zrzutka.jooq.model.tables.Summary.SUMMARY;
}
