/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import trzye.zrzutka.jooq.model.DefaultSchema;
import trzye.zrzutka.jooq.model.tables.records.AndroidMetadataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AndroidMetadata extends TableImpl<AndroidMetadataRecord> {

	private static final long serialVersionUID = -1307567476;

	/**
	 * The reference instance of <code>android_metadata</code>
	 */
	public static final AndroidMetadata ANDROID_METADATA = new AndroidMetadata();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AndroidMetadataRecord> getRecordType() {
		return AndroidMetadataRecord.class;
	}

	/**
	 * The column <code>android_metadata.locale</code>.
	 */
	public final TableField<AndroidMetadataRecord, String> LOCALE = createField("locale", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>android_metadata</code> table reference
	 */
	public AndroidMetadata() {
		this("android_metadata", null);
	}

	/**
	 * Create an aliased <code>android_metadata</code> table reference
	 */
	public AndroidMetadata(String alias) {
		this(alias, ANDROID_METADATA);
	}

	private AndroidMetadata(String alias, Table<AndroidMetadataRecord> aliased) {
		this(alias, aliased, null);
	}

	private AndroidMetadata(String alias, Table<AndroidMetadataRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AndroidMetadata as(String alias) {
		return new AndroidMetadata(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AndroidMetadata rename(String name) {
		return new AndroidMetadata(name, null);
	}
}
