/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import trzye.zrzutka.jooq.model.DefaultSchema;
import trzye.zrzutka.jooq.model.Keys;
import trzye.zrzutka.jooq.model.tables.records.ChargeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Charge extends TableImpl<ChargeRecord> {

	private static final long serialVersionUID = 1162349866;

	/**
	 * The reference instance of <code>charge</code>
	 */
	public static final Charge CHARGE = new Charge();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ChargeRecord> getRecordType() {
		return ChargeRecord.class;
	}

	/**
	 * The column <code>charge.amountPaid</code>.
	 */
	public final TableField<ChargeRecord, Long> AMOUNTPAID = createField("amountPaid", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>charge.amountToPay</code>.
	 */
	public final TableField<ChargeRecord, Long> AMOUNTTOPAY = createField("amountToPay", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>charge.chargeUniqueNumberForSorting</code>.
	 */
	public final TableField<ChargeRecord, Long> CHARGEUNIQUENUMBERFORSORTING = createField("chargeUniqueNumberForSorting", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>charge.charged_id</code>.
	 */
	public final TableField<ChargeRecord, Long> CHARGED_ID = createField("charged_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>charge.id</code>.
	 */
	public final TableField<ChargeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>charge.purchase_id</code>.
	 */
	public final TableField<ChargeRecord, Long> PURCHASE_ID = createField("purchase_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>charge</code> table reference
	 */
	public Charge() {
		this("charge", null);
	}

	/**
	 * Create an aliased <code>charge</code> table reference
	 */
	public Charge(String alias) {
		this(alias, CHARGE);
	}

	private Charge(String alias, Table<ChargeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Charge(String alias, Table<ChargeRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ChargeRecord> getPrimaryKey() {
		return Keys.PK_CHARGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ChargeRecord>> getKeys() {
		return Arrays.<UniqueKey<ChargeRecord>>asList(Keys.PK_CHARGE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Charge as(String alias) {
		return new Charge(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Charge rename(String name) {
		return new Charge(name, null);
	}
}
