/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import trzye.zrzutka.jooq.model.DefaultSchema;
import trzye.zrzutka.jooq.model.Keys;
import trzye.zrzutka.jooq.model.tables.records.ContributionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contribution extends TableImpl<ContributionRecord> {

	private static final long serialVersionUID = 95406066;

	/**
	 * The reference instance of <code>contribution</code>
	 */
	public static final Contribution CONTRIBUTION = new Contribution();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ContributionRecord> getRecordType() {
		return ContributionRecord.class;
	}

	/**
	 * The column <code>contribution.chargeUniqueNumberForSorting</code>.
	 */
	public final TableField<ContributionRecord, Long> CHARGEUNIQUENUMBERFORSORTING = createField("chargeUniqueNumberForSorting", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>contribution.colorId</code>.
	 */
	public final TableField<ContributionRecord, Integer> COLORID = createField("colorId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>contribution.endDate</code>.
	 */
	public final TableField<ContributionRecord, Date> ENDDATE = createField("endDate", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>contribution.id</code>.
	 */
	public final TableField<ContributionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>contribution.startDate</code>.
	 */
	public final TableField<ContributionRecord, Date> STARTDATE = createField("startDate", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>contribution.summary_id</code>.
	 */
	public final TableField<ContributionRecord, Long> SUMMARY_ID = createField("summary_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>contribution.title</code>.
	 */
	public final TableField<ContributionRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>contribution</code> table reference
	 */
	public Contribution() {
		this("contribution", null);
	}

	/**
	 * Create an aliased <code>contribution</code> table reference
	 */
	public Contribution(String alias) {
		this(alias, CONTRIBUTION);
	}

	private Contribution(String alias, Table<ContributionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Contribution(String alias, Table<ContributionRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ContributionRecord> getPrimaryKey() {
		return Keys.PK_CONTRIBUTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ContributionRecord>> getKeys() {
		return Arrays.<UniqueKey<ContributionRecord>>asList(Keys.PK_CONTRIBUTION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Contribution as(String alias) {
		return new Contribution(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Contribution rename(String name) {
		return new Contribution(name, null);
	}
}
