/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import trzye.zrzutka.jooq.model.DefaultSchema;
import trzye.zrzutka.jooq.model.Keys;
import trzye.zrzutka.jooq.model.tables.records.SummaryRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Summary extends TableImpl<SummaryRecord> {

	private static final long serialVersionUID = -1890750857;

	/**
	 * The reference instance of <code>summary</code>
	 */
	public static final Summary SUMMARY = new Summary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SummaryRecord> getRecordType() {
		return SummaryRecord.class;
	}

	/**
	 * The column <code>summary.colorPriceSumId</code>.
	 */
	public final TableField<SummaryRecord, Integer> COLORPRICESUMID = createField("colorPriceSumId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>summary.colorSummaryId</code>.
	 */
	public final TableField<SummaryRecord, Integer> COLORSUMMARYID = createField("colorSummaryId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>summary.id</code>.
	 */
	public final TableField<SummaryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>summary.isSortedDescending</code>.
	 */
	public final TableField<SummaryRecord, Short> ISSORTEDDESCENDING = createField("isSortedDescending", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>summary.preciseCalculation</code>.
	 */
	public final TableField<SummaryRecord, Short> PRECISECALCULATION = createField("preciseCalculation", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>summary.priceSum</code>.
	 */
	public final TableField<SummaryRecord, Long> PRICESUM = createField("priceSum", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>summary.sortedColumn</code>.
	 */
	public final TableField<SummaryRecord, String> SORTEDCOLUMN = createField("sortedColumn", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>summary</code> table reference
	 */
	public Summary() {
		this("summary", null);
	}

	/**
	 * Create an aliased <code>summary</code> table reference
	 */
	public Summary(String alias) {
		this(alias, SUMMARY);
	}

	private Summary(String alias, Table<SummaryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Summary(String alias, Table<SummaryRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SummaryRecord> getPrimaryKey() {
		return Keys.PK_SUMMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SummaryRecord>> getKeys() {
		return Arrays.<UniqueKey<SummaryRecord>>asList(Keys.PK_SUMMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Summary as(String alias) {
		return new Summary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Summary rename(String name) {
		return new Summary(name, null);
	}
}
