/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import trzye.zrzutka.jooq.model.tables.Contribution;
import trzye.zrzutka.jooq.model.tables.records.ContributionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributionDao extends DAOImpl<ContributionRecord, trzye.zrzutka.jooq.model.tables.pojos.Contribution, Integer> {

	/**
	 * Create a new ContributionDao without any configuration
	 */
	public ContributionDao() {
		super(Contribution.CONTRIBUTION, trzye.zrzutka.jooq.model.tables.pojos.Contribution.class);
	}

	/**
	 * Create a new ContributionDao with an attached configuration
	 */
	public ContributionDao(Configuration configuration) {
		super(Contribution.CONTRIBUTION, trzye.zrzutka.jooq.model.tables.pojos.Contribution.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(trzye.zrzutka.jooq.model.tables.pojos.Contribution object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>chargeUniqueNumberForSorting IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Contribution> fetchByChargeuniquenumberforsorting(Long... values) {
		return fetch(Contribution.CONTRIBUTION.CHARGEUNIQUENUMBERFORSORTING, values);
	}

	/**
	 * Fetch records that have <code>colorId IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Contribution> fetchByColorid(Integer... values) {
		return fetch(Contribution.CONTRIBUTION.COLORID, values);
	}

	/**
	 * Fetch records that have <code>endDate IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Contribution> fetchByEnddate(Date... values) {
		return fetch(Contribution.CONTRIBUTION.ENDDATE, values);
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Contribution> fetchById(Integer... values) {
		return fetch(Contribution.CONTRIBUTION.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public trzye.zrzutka.jooq.model.tables.pojos.Contribution fetchOneById(Integer value) {
		return fetchOne(Contribution.CONTRIBUTION.ID, value);
	}

	/**
	 * Fetch records that have <code>startDate IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Contribution> fetchByStartdate(Date... values) {
		return fetch(Contribution.CONTRIBUTION.STARTDATE, values);
	}

	/**
	 * Fetch records that have <code>summary_id IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Contribution> fetchBySummaryId(Long... values) {
		return fetch(Contribution.CONTRIBUTION.SUMMARY_ID, values);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Contribution> fetchByTitle(String... values) {
		return fetch(Contribution.CONTRIBUTION.TITLE, values);
	}
}
