/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import trzye.zrzutka.jooq.model.tables.Purchase;
import trzye.zrzutka.jooq.model.tables.records.PurchaseRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseDao extends DAOImpl<PurchaseRecord, trzye.zrzutka.jooq.model.tables.pojos.Purchase, Integer> {

	/**
	 * Create a new PurchaseDao without any configuration
	 */
	public PurchaseDao() {
		super(Purchase.PURCHASE, trzye.zrzutka.jooq.model.tables.pojos.Purchase.class);
	}

	/**
	 * Create a new PurchaseDao with an attached configuration
	 */
	public PurchaseDao(Configuration configuration) {
		super(Purchase.PURCHASE, trzye.zrzutka.jooq.model.tables.pojos.Purchase.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(trzye.zrzutka.jooq.model.tables.pojos.Purchase object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>colorId IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Purchase> fetchByColorid(Integer... values) {
		return fetch(Purchase.PURCHASE.COLORID, values);
	}

	/**
	 * Fetch records that have <code>contribution_id IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Purchase> fetchByContributionId(Long... values) {
		return fetch(Purchase.PURCHASE.CONTRIBUTION_ID, values);
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Purchase> fetchById(Integer... values) {
		return fetch(Purchase.PURCHASE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public trzye.zrzutka.jooq.model.tables.pojos.Purchase fetchOneById(Integer value) {
		return fetchOne(Purchase.PURCHASE.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Purchase> fetchByName(String... values) {
		return fetch(Purchase.PURCHASE.NAME, values);
	}

	/**
	 * Fetch records that have <code>price IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Purchase> fetchByPrice(Long... values) {
		return fetch(Purchase.PURCHASE.PRICE, values);
	}
}
