/**
 * This class is generated by jOOQ
 */
package trzye.zrzutka.jooq.model.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import trzye.zrzutka.jooq.model.tables.Summary;
import trzye.zrzutka.jooq.model.tables.records.SummaryRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SummaryDao extends DAOImpl<SummaryRecord, trzye.zrzutka.jooq.model.tables.pojos.Summary, Integer> {

	/**
	 * Create a new SummaryDao without any configuration
	 */
	public SummaryDao() {
		super(Summary.SUMMARY, trzye.zrzutka.jooq.model.tables.pojos.Summary.class);
	}

	/**
	 * Create a new SummaryDao with an attached configuration
	 */
	public SummaryDao(Configuration configuration) {
		super(Summary.SUMMARY, trzye.zrzutka.jooq.model.tables.pojos.Summary.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(trzye.zrzutka.jooq.model.tables.pojos.Summary object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>colorPriceSumId IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Summary> fetchByColorpricesumid(Integer... values) {
		return fetch(Summary.SUMMARY.COLORPRICESUMID, values);
	}

	/**
	 * Fetch records that have <code>colorSummaryId IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Summary> fetchByColorsummaryid(Integer... values) {
		return fetch(Summary.SUMMARY.COLORSUMMARYID, values);
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Summary> fetchById(Integer... values) {
		return fetch(Summary.SUMMARY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public trzye.zrzutka.jooq.model.tables.pojos.Summary fetchOneById(Integer value) {
		return fetchOne(Summary.SUMMARY.ID, value);
	}

	/**
	 * Fetch records that have <code>isSortedDescending IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Summary> fetchByIssorteddescending(Short... values) {
		return fetch(Summary.SUMMARY.ISSORTEDDESCENDING, values);
	}

	/**
	 * Fetch records that have <code>preciseCalculation IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Summary> fetchByPrecisecalculation(Short... values) {
		return fetch(Summary.SUMMARY.PRECISECALCULATION, values);
	}

	/**
	 * Fetch records that have <code>priceSum IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Summary> fetchByPricesum(Long... values) {
		return fetch(Summary.SUMMARY.PRICESUM, values);
	}

	/**
	 * Fetch records that have <code>sortedColumn IN (values)</code>
	 */
	public List<trzye.zrzutka.jooq.model.tables.pojos.Summary> fetchBySortedcolumn(String... values) {
		return fetch(Summary.SUMMARY.SORTEDCOLUMN, values);
	}
}
